// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvcdxdyokiauhvkgtwei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2Y2R4ZHlva2lhdWh2a2d0d2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNDM3NTEsImV4cCI6MjA1NDgxOTc1MX0.sf7JbJr2uP5kbiCvcVNn80xMU6alanUicJWm9EPeEiw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
